### ISSUE TITLE
How do can I get cwlformat to work on Py3.5 

### ISSUE THREAD

**Issue by ambarishK** [rabix/cwl-format#10]
There is an error in cwl-format.

````
(env) ngsap2@ubuntu:~/cwl-format$ cwl-format /home/ngsap2/alignmentDocker.cwl > alignmentNewDocker.cwl
Traceback (most recent call last):
  File "/home/ngsap2/.local/bin/cwl-format", line 7, in <module>
    from cwlformat.formatter import main
  File "/home/ngsap2/.local/lib/python3.5/site-packages/cwlformat/formatter.py", line 105
    description=f"Rabix/cwl-format v{__version__}\n"
                                                   ^
SyntaxError: invalid syntax
````

**Comment by kaushik-work** [comment]
Hi @ambarishK , thank you for reporting this. Could you send the output of `cwl-format --version` please? The latest release (2020.04.30) does not show this.

**Comment by ambarishK** [comment]
Yes sir. I changed my python environment from python 3.5 to python 3.6 and updated dependencies after installing setup.py.

It is working fine now.

Thank you so much sir.

**Comment by kaushik-work** [comment]
You are most welcome @ambarishK .
