### ISSUE TITLE
Release for Python 3.6

### ISSUE THREAD

**Issue by illusional** [rabix/cwl-format#11]
Hi, I issued a PR (#5) for fixing Python 3.6. Just wondering if there's a release planned for this, or if there's something else that it's waiting on.

**Comment by kaushik-work** [comment]
I'll make a release on PyPi.

**Comment by kaushik-work** [comment]
A new release on PyPi has been made. Thanks!

**Comment by illusional** [comment]
Thanks @kaushik-work!
