### ISSUE TITLE
How to convert a packed CWL workflow to a "normal" workflow supported by Rabix composer

### ISSUE THREAD

**Issue by altairwei** [rabix/cwl-format#14]
If I use the `cwltool --pack` command, I will get a CWL document that contains the `$graph` key, but Rabix composer does not support this type of CWL document. How do I convert a CWL document that contains the `$graph` key into a "normal" CWL document?

**Comment by kaushik-work** [comment]
@altairwei you can use `cwlpack` from `sbpack` (https://github.com/rabix/sbpack) to get a traditional CWL file.

**Comment by kaushik-work** [comment]
@altairwei can you expand a little on your use case - what are you trying to do from a bigger picture? Thanks!

**Comment by altairwei** [comment]
BD Rhapsody provides a CWL workflow for running scRNA-Seq analysis at https://bitbucket.org/CRSwDev/cwl, but these CWL documents should be generated using the `cwltool --pack` command, as they contain `$graph` key. My own scRNA-Seq project has special needs, so I had to modify the CWL workflow provided by BD Rhapsody, but Rabix Composer does not support this CWL documentation.

**Comment by kaushik-work** [comment]
The packed format is not that common. Is there any way to give the BD team feedback that they should release the CWL as a folder of CWL files? This is the community standard.

**Comment by altairwei** [comment]
`cwlpack` is used to package the CWL workflow, right? I checked the source code for `sbpack/unpack.py` and found that it might not do what I need.

**Comment by kaushik-work** [comment]
@altairwei sorry, yes, I initially thought you wanted to pack a CWL workflow yourself.

**Comment by mr-c** [comment]
@altairwei Can you try https://github.com/common-workflow-language/cwl-utils/blob/main/cwl_utils/graph_split.py ?

**Comment by altairwei** [comment]
I got some exceptions when I used your script to split this document. https://gist.github.com/altairwei/6a0097db95cad23de36f825ed3b9f4b0#file-rhapsody_wta_1-8-packed-cwl

Nevertheless, I've used some of `cwltool`'s internal modules to split CWL documents in an ugly way.
https://gist.github.com/altairwei/6a0097db95cad23de36f825ed3b9f4b0#file-cwlunpack-py

**Comment by mr-c** [comment]
Thank you @altairwei for that example; I've fixed those errors at https://github.com/common-workflow-language/cwl-utils/blob/6edb6e26f61e6497a3aeb279e77295bc26fb0cdd/cwl_utils/graph_split.py

You'll want to run `cwl-format` on the result :-D

Soon the changes to `graph_split.py` will be merged in and I'll make a new release of `cwl-utils`

**Comment by mr-c** [comment]
@altairwei Your `cwlunpack.py` has a nicer command line interface. Would you like to send a PR in a few days to update `graph_split.py` to use something similar?

**Comment by altairwei** [comment]
> @altairwei Your `cwlunpack.py` has a nicer command line interface. Would you like to send a PR in a few days to update `graph_split.py` to use something similar?

@mr-c Yes, I'd be glad to do it.

**Comment by altairwei** [comment]
@mr-c
After your changes have been merged, I'm going to design a nice command line interface for `graph_split.py`. Then I'm going to include `cwl-format` as a dependency so we can get nicely formatted cwl documents in one step. Do you think this is an acceptable solution?

**Comment by mr-c** [comment]
@altairwei The changes have been merged. Thanks for agreeing up add your update! Yes, it is fine to include `cwl-format` as an optional dependency. There should be a flag to skip it, for those who don't need it.

**Comment by mr-c** [comment]
@kaushik-work you can probably close this issue, we can continue over at https://github.com/common-workflow-language/cwl-utils
