### ISSUE TITLE
Add an inline modification mode

### ISSUE THREAD

**Issue by mr-c** [rabix/cwl-format#3]
I am happy to contribute this as well, if no one else wants to

**Comment by kaushik-work** [comment]
@mr-c sorry, I didn't see this earlier - forgot to watch this repo. Is the idea that the command line will allow the user to overwrite the original tool if they really want to? Absolutely, could add a flag, say `--inplace`, that doesn't write to stdout but rather over writes the original file. Would that work?

**Comment by mr-c** [comment]
`--inplace` is exactly what I had in mind, yes!
