### ISSUE TITLE
importlib.resources breaks Python <3.7

### ISSUE THREAD

**Issue by illusional** [rabix/cwl-format#5]
I updated cwlformat today and noticed that importlib.resources breaks Python < 3.7 which won't work. I tried installed `importlib-metada` but this also doesn't work.

Just wondering if there are potentially any suggestions? I'm happy to PR convert `keyorder.yaml` into a Python files so it can be imported and used.

**Comment by illusional** [comment]
I've created a PR to address this, but feel free to close it if that's not the way you want to go. Otherwise, might be worth advertising that cwl-format requires Python 3.7+.

**Comment by kaushik-work** [comment]
Hi @illusional thanks for the PR. We can discuss further, but I'd like to keep the keyorder in YAML to leave open the possibility for other (non-python) implementations to use the file. The repo is intended as a specification as well as an implementation.

I had a colleague ask about this too. Is Py 3.7 too new? The setup.py does lay out that the minimum version of Python is 3.7.

Again, happy to discuss further.

**Comment by illusional** [comment]
I've worked a cross a few clusters which have mostly used Python 3.6.x as a default, and sometimes have a newer version. You're right though it's in the setup.py, maybe PIP isn't respecting that properly.

Another solution is to fallback to the `importlib_resources` module:

```
try:
    from importlib.resources import read_text
except ImportError:
    from importlib_resources import read_text
```

From my quick test this works. Happy to issue a PR for this too.
